### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by leonardoz15** [burrowss/DnD_DiceRoller#3]
### Date of the review: 11/8/18
Inspection rate: 1 hour
Defect rate: 1/review
Defect density: 0
### Checklist
- [x] Code Formatting
C# code looks clean and follows coding standards
- [x] Coding Best Practices
No comments, but there isn't alot of code to begin with. Kept it simple which is good.
- [x] Code Readability
The randomDirectionalForce.cs is named correctly as it applies a random directional force
- [x] Code Testability
Easily ran in Unity engine, physics can be applied easily by editing values in the editor.
- [x] Code Reliability
Good starting point, but need to get die to land flush with the ground so it can be read once rolled.
- [x] Usability
The idea is great, it just needs to be refined to a single die and smoother physics and it will be fine.

**Comment by burrowss** [comment]
Great points. Currently working on getting the die to be flush with the ground, but not ready to be implemented yet

**Comment by burrowss** [comment]
Was able to get the die to land flush to the ground. Getting ready to tackle my next issue

**Comment by burrowss** [comment]
All points have been addressed other than choosing a die. That will be a feature added later.
