### ISSUE TITLE
Software Project Review #2

### ISSUE THREAD

**Issue by everitt-andrew** [burrowss/DnD_DiceRoller#5]
The project appears to be complete or nearly there. I am especially impressed with the formatting of the README file. Personally, I wouldn't be too worried about the file's load time being so long. Finally, I don't think that there are many issues left to fix. Overall, incredible work. 

I would recommend:
- Fixing TravisCI (if possible)
- Adding screenshots demonstrating program running
- Finding a way to track dice rolls (a history tab/option) or the ability to select desired dice or multiples of the same (as you mentioned in the enhancement issue)

**Comment by burrowss** [comment]
Travis has been fixed, and the description for running the program has been updated, although screenshots may come later. Thanks for the suggestions
